### ISSUE TITLE
feature: configure spaces and rooms in config.yaml

### ISSUE THREAD

**Issue by ayushin** [elokapina/bubo#33]
This is really a very useful project!

It would be great if one could pre-configure spaces and rooms structure in the config.yaml instead of having to create them manually like so:

```
spaces:
    - space_a:
       description: "My awesome space"
       spaces:
       - subspace b:
          rooms:
          - rooom_a:
             alias: "#roomA"
             description: "Welcome to Room A"
             public: no
             encrypted: no
           - room_b:
```

And have bubo compare the database vs the config.yaml on startup and make changes.
